#!/usr/bin/env ruby
# frozen_string_literal: true

require 'sequel/pgt_outbox'
require 'optparse'

autovacuum = true
notify = false
notify_channel = nil

opts = OptionParser.new do |o|
  o.banner = 'Usage: outboxify [options] <db uri> <table>'
  o.on('--no-autovacuum') { autovacuum = false }
  o.on('--notify') { notify = true }
  o.on('--notify-channel CHANNEL') { |c| notify_channel = c }
end
opts.parse!

db_uri = ARGV.shift
if db_uri.nil?
  warn 'missing db uri'
  puts opts
  exit 1
end

DB = Sequel.connect db_uri
DB.extension :pgt_outbox

table = ARGV.shift
if table.nil?
  warn 'missing table'
  puts opts
  exit 2
end

options = { autovacuum:, notify: }
options[:notify_channel] = notify_channel if notify_channel
function = DB.pgt_outbox_setup(table, **options)
DB.pgt_outbox_events(table, function)
