---
name: Validations

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  workflow_call:
  pull_request:

jobs:
  validate_ruby:
    name: Ruby Tests
    uses: ./.github/workflows/main.yaml
